name: bumdes_collection_pro
description: "Professional debt collection and member management system designed specifically for BUMDes (Village-owned Enterprises) to efficiently track, monitor, and collect outstanding member debts with comprehensive collector and supervisor tools."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  sizer: ^2.0.15
  shared_preferences: ^2.2.2
  dio: ^5.7.0
  connectivity_plus: ^5.0.2
  fl_chart: ^0.65.0
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  local_auth: ^2.1.8
  permission_handler: ^11.3.1
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  csv: ^6.0.0
  syncfusion_flutter_xlsio: ^30.1.42
  pdf: ^3.11.3
  share_plus: ^11.0.0

  web: any
  camera: any
  image_picker: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/